export enum ActionType {
    // CONTENT LOAD REDUCER
    CONTENT_LOADING = "CONTENT_LOADING",
    CONTENT_VIDEO_LOADING = "CONTENT_VIDEO_LOADING",
    CONTENT_MUSIC_LOADING = "CONTENT_MUSIC_LOADING",
    CONTENT_SOUNDS_LOADING = "CONTENT_SOUNDS_LOADING",
    CONTENT_FONT_LOADING = "CONTENT_FONT_LOADING",
    CONTENT_FINGERPRINT_INIT = "CONTENT_FINGERPRINT_INIT",
    CONTENT_REFRESH = "CONTENT_REFRESH",
    CONTENT_LOADING_BAR = "CONTENT_LOADING_BAR",
    CONTENT_SET_VIDEO = "CONTENT_SET_VIDEO",
    
    // GAME REDUCER
    GAME_LOADING = "GAME_LOADING",
    GAME_SET_USER_POINT = "GAME_SET_USER_POINT",
    GAME_REFRESH = "GAME_REFRESH",
    GAME_CHANGE_STATUS = "GAME_CHANGE_STATUS",
    GAME_SET_STREAK = "GAME_SET_STREAK",
}