export const Constant = {
    APP_NAME: "NoteQuizz",
    AUTH_USER: "USER",
    GUEST_USER: "GUEST",
    START_BUTTON: "Start Game",
    EXERCISE_BUTTON: "Exercise Mode",
    SETTINGS_BUTTON: "Settings",
    HIGH_SCORES_BUTTON: "High Scores",
    PLAY_AGAIN_BUTTON: "Play Again",
    SAVE_BUTTON: "Save",
    RESET_DEFAULT_BUTTON: "Reset to Defaults",
    CANCEL_BUTTON: "Cancel",
    MAIN_MENU_BUTTON: "Main Menu",
    TEST_SOUNDS_BUTTON: "Test Sounds",
    STATS_HEADER: "Here The Stats",
    GAME_OVER_HEADER: "Game Over",
    SETTINGS_HEADER: "Game Settings",
    MAIN_MENU_SOUND_LABEL: "Main Menu Music Volume",
    SETTINGS_GAME_DURATION_LABEL: "Game Duration(seconds)",
    SETTINGS_SFX_LABEL: "Sound Effects",
    SETTINGS_OSCILLATOR_LABEL: "Sound Wave Type",
    SETTINGS_DISPLAY_MODE_LABEL: "Answer Display Mode",
    SETTINGS_TAB_GENERAL: "General",
    SETTINGS_TAB_AUDIO: "Audio",
    SETTINGS_TAB_CONTROLS: "Controls",
    SETTINGS_BUTTON_KEYS_LABEL: "Button Shortcuts",
    SETTINGS_OCTAVES_LABEL: "Octave Ranges",
    SETTINGS_SHOW_OCTAVE_LABEL: "Show Octave Badge",
    SETTINGS_DESC: "Adjust the game settings to your preference. You can change the game duration and the points gained or lost for correct and wrong answers.",
    SETTINGS_OSCILLATOR_SINE: "Sine (Smooth)",
    SETTINGS_OSCILLATOR_SQUARE: "Square (Retro/Sharp)",
    SETTINGS_OSCILLATOR_SAWTOOTH: "Sawtooth (Rich/Tough)",
    SETTINGS_OSCILLATOR_TRIANGLE: "Triangle (Like Flute)",
    SETTINGS_DISPLAY_MODE_SOLFEGE: "Solfege (Do, Re, Mi)",
    SETTINGS_NOTE_SOUND_TYPE_LABEL: "Note Sound Type",
    SETTINGS_NOTE_SOUND_TYPE_PIANO: "Piano",
    SETTINGS_NOTE_SOUND_TYPE_OSCILLATOR: "Oscillator",
    SETTINGS_DISPLAY_MODE_SCIENTIFIC: "Scientific (C4, D4...)",
    HIGH_SCORES_HEADER: "High Scores",
    SETTINGS_OCTAVES_LABEL_PREFIX: "Octave",
    SETTINGS_OCTAVES_LABEL_SUFFIX: " Ranges",
    CONTINUE_BUTTON: "Click To Continue",
    POINTS: "Point(s)",
    CORRECT_ANSWER: "Correct(s)",
    WRONG_ANSWER: "Wrong(s)",
    STREAK: "Streak(s)",
    OCTAVE_NAME: "Octave",
    CONFETTI_CELEBRATION_1: "Awesome!",
    CONFETTI_CELEBRATION_2: "Perfect!",
    CONFETTI_CELEBRATION_3: "Super!",
    CONFETTI_CELEBRATION_4: "Wonderful!",
    CONFETTI_CELEBRATION_5: "Unstoppable!",
    GAME_DURATION_MIN:  60,
    GAME_DURATION_MAX: 300,
    GAINED_POINT: 1,
    RESET_POINT: -1,
    DEFAULT_POINT: 0,
}